USE EQLIFE

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_WARNINGS ON
GO

SELECT DISTINCT
	'PrecentiaLife' AS 'App Name',
	'[' +s.SUSERID+ ']' + ' - ' + s.SNAME AS 'Username',
	s.SLOGINSTAT AS 'Status',
	s.DUSERCREATEDT AS 'Create Date',
	s.TMODDT AS 'Change Date',
	s.TLASTPASSCHGDT AS 'Last Change Password',
	s.SNAME AS 'Full Name',
	dept.SDESC As 'Dept Name',
	ghd.SGROUP AS 'Group Name',
	ghd.SDESC,
	module.LSEQID AS 'Menu Id',
	module.SPROGID AS 'Menu Name'
FROM 
	EQLIFE.PLS.SCMUSER AS s
	INNER JOIN
	(SELECT * FROM EQLIFE.PLS.PDTMASTERDET WHERE LFKMASTERHDR = 149)AS dept
	ON s.SDEPTCODE = dept.SCODE
	INNER JOIN
	EQLIFE.PLS.SCMUSERACCESS AS usg
	ON s.LSEQID = usg.LFKUSER
	INNER JOIN
	EQLIFE.PLS.SCMGROUPHDR AS ghd
	ON usg.LFKGROUPHDR = ghd.LSEQID
	INNER JOIN
	EQLIFE.PLS.SCMGROUPDET AS grpdet
	ON grpdet.LFKGROUPHDR = ghd.LSEQID
	LEFT JOIN
	EQLIFE.PLS.SCXUSERLOGHDR AS loghd
	ON loghd.LFKUSER = S.LSEQID
	LEFT JOIN
	EQLIFE.PLS.SCMMODULE AS module
	ON module.LSEQID = grpdet.LFKMODULE
--WHERE
	--SNAME IN
	--(
	--	 'HERLINA'
	--	,'INDRI HAPSARI'
	--	,'INDRI HAPSARI 2'
	--	,'HERETS TOBIAS'
	--	,'LAMHOT SIMANJUNTAK'
	--	,'JERRY SETIAWAN'
	--	,'LINA LAILA'
	--	,'NILASARI'
	--	,'GLORY WATTIMENA'
	--	,'ANISA FIRDAUSI'
	--	,'ASHAR DENNI SETIAWAN'
	--	,'NURDIANA ISNAENI'
	
	--)
GROUP BY
	s.SUSERID ,
	s.SLOGINSTAT ,
	s.DUSERCREATEDT ,
	s.TMODDT ,
	s.TLASTPASSCHGDT ,
	s.SUSERID ,
	s.SNAME ,
	dept.SDESC,
	ghd.SGROUP,
	ghd.SDESC,
	module.LSEQID,
	module.SPROGID
ORDER BY
	'[' +s.SUSERID+ ']' + ' - ' + s.SNAME
	



--HERLINA
--INDRI HAPSARI
--INDRI HAPSARI 2
--HERETS TOBIAS
--LAMHOT SIMANJUNTAK
--JERRY SETIAWAN
--LINA LAILA
--NILASARI
--GLORY WATTIMENA
--ANISA FIRDAUSI
--ASHAR DENNI SETIAWAN
--NURDIANA ISNAENI